executable            = Run_Analyser_short.py
arguments             =  --config_file $(config_File) --outputname $(output_name)_$(ProcId) --list $(name_list)$(ProcId) --dirlist $(dir_list)
output                = $(output_dir)/Output_$(output_name)_$(ProcId).txt
error                 = $(errors_dir)/Errors_$(output_name)_$(ProcId).txt
log                   = $(logs_dir)/job.$(ClusterId).$(ProcId).log
transfer_output_files   = ""
+JobFlavour            = "tomorrow"
queue                  $(Njob)
